  services:
    clematis-storage-api:
      container_name: clematis-storage-api
      image: clematis.storage.api:latest
      networks:
        - clematis_str
      ports:
        - "18088:8080"
        - "15091:5000"
        - "15092:5001"
      env_file:
        - storage_api_qa.env
      volumes:
        - /home/clematis/storage/logs:/var/log/clematis
        - /home/clematis/storage/files:/home/clematis/storage/files
      restart: unless-stopped

  networks:
    clematis_str:
      driver: bridge


